name: mobile_app_theraphy
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  image_picker: ^0.8.0+6
  video_player: ^2.3.7
  shared_preferences: ^2.1.2 
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  firebase_auth: ^4.6.3 
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  flutter_ffmpeg: ^0.4.2
  chewie: ^1.7.1
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logotheraphy.png
    - assets/background.png
