name: mobile_app_theraphy
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  image_picker: ^0.8.0+6
  video_player: ^2.3.7
  shared_preferences: ^2.1.2 
  intl: ^0.18.1
  firebase_auth: ^4.6.3 
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  flutter_ffmpeg: any
  chewie: ^1.7.1
  curved_navigation_bar: ^1.0.3
  syncfusion_flutter_charts: ^23.1.44
  percent_indicator: ^3.0.1
  flutter_svg: ^1.1.0
  touchable: ^1.0.2
  freezed_annotation: ^2.0.3
  rotation_stage: ^0.0.3
  fluttertoast: ^8.2.4
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.1
  flutter_phone_direct_caller: ^2.0.1
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  flutter_launcher_icons:
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logotheraphy.png"
  adaptive_icon_background: "assets/logotheraphy.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logotheraphy.png
    - assets/background.png
    - assets/Thinking.png
    - assets/appointments3.png
    - assets/consultation.png
    - assets/m_back.svg
    - assets/m_front.svg
    - assets/m_left.svg 
    - assets/m_right.svg
    - assets/iot.png

 

